run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - errcheck
    # gofumpt is stricter than gofmt; optional in local dev
    - gocritic
  disable:
    - depguard

linters-settings:
  gofumpt:
    extra-rules: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
