repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'gofmt -s -l . | tee /dev/stderr | (! grep ".")'
        language: system
        pass_filenames: false
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'golangci-lint run ./...'
        language: system
        pass_filenames: false
      - id: go-test
        name: go test (unit)
        entry: go test ./... -count=1
        language: system
        pass_filenames: false
