name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-unit:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...

      - name: go vet
        run: go vet ./...

      - name: go test (unit)
        run: go test ./... -v -count=1

  e2e:
    name: End-to-End Examples
    runs-on: ubuntu-latest
    needs: lint-and-unit
    if: ${{ secrets.OLLAMA_BASE_URL != '' && secrets.OLLAMA_MODEL != '' }}
    env:
      OLLAMA_BASE_URL: ${{ secrets.OLLAMA_BASE_URL }}
      OLLAMA_MODEL: ${{ secrets.OLLAMA_MODEL }}
      OLLAMA_EMBED_MODEL: ${{ secrets.OLLAMA_EMBED_MODEL }}
      RUN_E2E: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run E2E examples tests
        run: go test ./examples -v -count=1
